---
# tasks file for apt-cacher-ng_controller
- name: Install apt-cacher-ng
  apt:
    name: apt-cacher-ng

- name: Configure apt-cacher-ng
  template:
    src: templates/acng.conf.j2
    dest: /etc/apt-cacher-ng/acng.conf
    backup: yes
  notify: Restart apt-cacher-ng

- name: Configure the local Aptitude client to use apt-cacher-ng
  template:
    src: templates/02proxy-startup.j2
    dest: /etc/apt/apt.conf.d/02proxy
